-- Create diamond_collaborators table for group direct-solve
create table public.diamond_collaborators (
  id bigint generated by default as identity primary key,
  diamond_id bigint not null references public.diamonds(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (diamond_id, user_id)
);

-- Enable RLS
alter table public.diamond_collaborators enable row level security;

-- RLS: anyone can read, diamond owner and admins can manage
create policy "Anyone can read diamond collaborators"
  on public.diamond_collaborators for select
  using (true);

create policy "Diamond owners can add collaborators"
  on public.diamond_collaborators for insert
  to authenticated
  with check (
    exists (
      select 1 from public.diamonds
      where id = diamond_id and user_id = auth.uid()
    )
  );

create policy "Diamond owners can remove collaborators"
  on public.diamond_collaborators for delete
  to authenticated
  using (
    exists (
      select 1 from public.diamonds
      where id = diamond_id and user_id = auth.uid()
    )
  );

-- Grants for Data API
grant select, insert, delete on table public.diamond_collaborators to authenticated;

-- Update the award function to also give 10pts to all collaborators
create or replace function public.award_direct_solve_points()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  collab record;
begin
  if new.status = 'accepted' and old.status != 'accepted' and new.linked_grievance_id is not null and not new.direct_solve_awarded then
    new.direct_solve_awarded := true;

    -- Award 10 points to the post owner
    update public.profiles
    set points = coalesce(points, 0) + 10
    where id = new.user_id;

    -- Award 10 points to each collaborator
    for collab in
      select user_id from public.diamond_collaborators
      where diamond_id = new.id
    loop
      update public.profiles
      set points = coalesce(points, 0) + 10
      where id = collab.user_id;
    end loop;
  end if;
  return new;
end;
$$;

-- Admin functions for diamond management

-- Add a collaborator (admin only, or post owner)
create or replace function public.add_diamond_collaborator(diamond_id bigint, collaborator_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.diamond_collaborators (diamond_id, user_id)
  values (diamond_id, collaborator_id)
  on conflict (diamond_id, user_id) do nothing;
end;
$$;

-- Remove a collaborator (admin or post owner)
create or replace function public.remove_diamond_collaborator(diamond_id bigint, collaborator_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.diamond_collaborators
  where diamond_id = remove_diamond_collaborator.diamond_id
    and user_id = remove_diamond_collaborator.collaborator_id;
end;
$$;

-- Accept a diamond (admin only) - awards points via trigger
create or replace function public.accept_diamond(diamond_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.diamonds
  set status = 'accepted'
  where id = diamond_id
    and status = 'pending'
    and linked_grievance_id is not null;
end;
$$;

-- Reject a diamond (admin only)
create or replace function public.reject_diamond(diamond_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.diamonds
  set status = 'rejected'
  where id = diamond_id
    and status = 'pending'
    and linked_grievance_id is not null;
end;
$$;

-- Get pending diamonds for admin review (includes collaborator count)
create or replace function public.get_pending_diamonds()
returns table (
  id bigint,
  user_id uuid,
  body text,
  image_urls text[],
  linked_grievance_id uuid,
  created_at timestamptz,
  user_name text,
  user_avatar text,
  collaborator_count bigint,
  grievance_title text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  return query
  select
    d.id,
    d.user_id,
    d.body,
    d.image_urls,
    d.linked_grievance_id,
    d.created_at,
    coalesce(p.username, 'Unknown'),
    p.avatar_url,
    (select count(*) from public.diamond_collaborators dc where dc.diamond_id = d.id),
    coalesce(g.title, '')
  from public.diamonds d
  left join public.profiles p on p.id = d.user_id
  left join public.grievances g on g.id = d.linked_grievance_id
  where d.status = 'pending'
    and d.linked_grievance_id is not null
  order by d.created_at desc;
end;
$$;

grant execute on function public.add_diamond_collaborator to authenticated;
grant execute on function public.remove_diamond_collaborator to authenticated;
grant execute on function public.accept_diamond to authenticated;
grant execute on function public.reject_diamond to authenticated;
grant execute on function public.get_pending_diamonds to authenticated;
