create table public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  author_id uuid not null references auth.users(id) on delete cascade,
  is_pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.announcements enable row level security;

create policy "Everyone can read announcements"
  on public.announcements for select
  using (true);

create policy "Officials can insert announcements"
  on public.announcements for insert
  to authenticated
  with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'official'
    )
  );

create policy "Officials can update their own announcements"
  on public.announcements for update
  to authenticated
  using (
    author_id = auth.uid()
    and exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'official'
    )
  );

create policy "Officials can delete their own announcements"
  on public.announcements for delete
  to authenticated
  using (
    author_id = auth.uid()
    and exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'official'
    )
  );

create or replace function public.set_announcement_updated_at()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_announcement_updated_at
  before update on public.announcements
  for each row
  execute function public.set_announcement_updated_at();
