-- Create diamond_upvotes and diamond_comments tables for social features
-- RLS, policies, grants, toggle RPC, and updated_at trigger

create table if not exists public.diamond_upvotes (
  id bigint generated by default as identity primary key,
  diamond_id bigint not null references public.diamonds(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (diamond_id, user_id)
);

create table if not exists public.diamond_comments (
  id bigint generated by default as identity primary key,
  diamond_id bigint not null references public.diamonds(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.diamond_upvotes enable row level security;
alter table public.diamond_comments enable row level security;

do $$ begin create policy "Anyone can read diamond upvotes" on public.diamond_upvotes for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "Users can insert own upvote" on public.diamond_upvotes for insert to authenticated with check (user_id = auth.uid()); exception when duplicate_object then null; end $$;
do $$ begin create policy "Users can delete own upvote" on public.diamond_upvotes for delete to authenticated using (user_id = auth.uid()); exception when duplicate_object then null; end $$;

do $$ begin create policy "Anyone can read diamond comments" on public.diamond_comments for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "Users can insert own comment" on public.diamond_comments for insert to authenticated with check (user_id = auth.uid()); exception when duplicate_object then null; end $$;
do $$ begin create policy "Users can update own comment" on public.diamond_comments for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid()); exception when duplicate_object then null; end $$;
do $$ begin create policy "Users can delete own comment" on public.diamond_comments for delete to authenticated using (user_id = auth.uid()); exception when duplicate_object then null; end $$;

grant select, insert, delete on public.diamond_upvotes to authenticated;
grant select, insert, update, delete on public.diamond_comments to authenticated;

create or replace function public.toggle_diamond_upvote(p_diamond_id bigint)
returns table (new_upvote_count bigint, is_upvoted boolean)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if exists (select 1 from public.diamond_upvotes where diamond_id = p_diamond_id and user_id = v_user_id) then
    delete from public.diamond_upvotes where diamond_id = p_diamond_id and user_id = v_user_id;
  else
    insert into public.diamond_upvotes (diamond_id, user_id) values (p_diamond_id, v_user_id);
  end if;

  return query
  select
    (select count(*) from public.diamond_upvotes where diamond_id = p_diamond_id) as new_upvote_count,
    exists (select 1 from public.diamond_upvotes where diamond_id = p_diamond_id and user_id = v_user_id) as is_upvoted;
end;
$$;

grant execute on function public.toggle_diamond_upvote to authenticated;

create or replace function public.update_diamond_comment_timestamp()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_diamond_comment_updated on public.diamond_comments;
create trigger trg_diamond_comment_updated
  before update on public.diamond_comments
  for each row
  execute function public.update_diamond_comment_timestamp();
