-- Create the diamonds table for user posts
create table public.diamonds (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  image_urls text[] not null default '{}',
  created_at timestamptz not null default now()
);

-- Enable RLS
alter table public.diamonds enable row level security;

-- RLS policies
create policy "Anyone can read diamonds"
  on public.diamonds for select
  using (true);

create policy "Authenticated users can insert their own diamonds"
  on public.diamonds for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update their own diamonds"
  on public.diamonds for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own diamonds"
  on public.diamonds for delete
  to authenticated
  using (auth.uid() = user_id);

-- Grants for the Data API
grant usage on schema public to anon, authenticated;
grant select on table public.diamonds to anon, authenticated;
grant insert, update, delete on table public.diamonds to authenticated;

-- Create storage bucket for diamond images
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'diamonds',
  'diamonds',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;
