-- Create diamond_shares table for tracking shares (like Facebook-style share count)
-- Add admin_remove_diamond RPC for admin moderation

create table if not exists public.diamond_shares (
  id bigint generated by default as identity primary key,
  diamond_id bigint not null references public.diamonds(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (diamond_id, user_id)
);

alter table public.diamond_shares enable row level security;

do $$ begin create policy "Anyone can read diamond shares" on public.diamond_shares for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "Users can insert own share" on public.diamond_shares for insert to authenticated with check (user_id = auth.uid()); exception when duplicate_object then null; end $$;
do $$ begin create policy "Users can delete own share" on public.diamond_shares for delete to authenticated using (user_id = auth.uid()); exception when duplicate_object then null; end $$;

grant select, insert, delete on public.diamond_shares to authenticated;

create or replace function public.toggle_diamond_share(p_diamond_id bigint)
returns table (new_share_count bigint, is_shared boolean)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if exists (select 1 from public.diamond_shares where diamond_id = p_diamond_id and user_id = v_user_id) then
    delete from public.diamond_shares where diamond_id = p_diamond_id and user_id = v_user_id;
  else
    insert into public.diamond_shares (diamond_id, user_id) values (p_diamond_id, v_user_id);
  end if;

  return query
  select
    (select count(*) from public.diamond_shares where diamond_id = p_diamond_id) as new_share_count,
    exists (select 1 from public.diamond_shares where diamond_id = p_diamond_id and user_id = v_user_id) as is_shared;
end;
$$;

grant execute on function public.toggle_diamond_share to authenticated;

create or replace function public.admin_remove_diamond(p_diamond_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role = 'admin'
  ) then
    raise exception 'Only admins can remove posts';
  end if;

  delete from public.diamonds
  where id = p_diamond_id;
end;
$$;

grant execute on function public.admin_remove_diamond to authenticated;
