-- Diamond review notifications must only be generated by trusted review actions.
-- Restrict direct client updates to editable post text; status changes go through
-- role-checked SECURITY DEFINER functions.
revoke update on table public.diamonds from anon, authenticated;
grant update (body) on table public.diamonds to authenticated;

create or replace function public.add_diamond_collaborator(
  diamond_id bigint,
  collaborator_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1
    from public.diamonds d
    where d.id = add_diamond_collaborator.diamond_id
      and d.user_id = (select auth.uid())
  ) and not exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.role in ('admin', 'super_admin')
  ) then
    raise exception 'Only the post owner or an admin can add collaborators'
      using errcode = '42501';
  end if;

  insert into public.diamond_collaborators (diamond_id, user_id)
  values (add_diamond_collaborator.diamond_id, add_diamond_collaborator.collaborator_id)
  on conflict on constraint diamond_collaborators_diamond_id_user_id_key do nothing;
end;
$$;

create or replace function public.remove_diamond_collaborator(
  diamond_id bigint,
  collaborator_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1
    from public.diamonds d
    where d.id = remove_diamond_collaborator.diamond_id
      and d.user_id = (select auth.uid())
  ) and not exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.role in ('admin', 'super_admin')
  ) then
    raise exception 'Only the post owner or an admin can remove collaborators'
      using errcode = '42501';
  end if;

  delete from public.diamond_collaborators as dc
  where dc.diamond_id = remove_diamond_collaborator.diamond_id
    and dc.user_id = remove_diamond_collaborator.collaborator_id;
end;
$$;

create or replace function public.accept_diamond(diamond_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_linked_grievance_id uuid;
  v_grievance_reporter_id uuid;
begin
  if not exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.role in ('admin', 'super_admin')
  ) then
    raise exception 'Only an admin can accept Diamond solutions'
      using errcode = '42501';
  end if;

  select d.linked_grievance_id, g.reporter_id
  into v_linked_grievance_id, v_grievance_reporter_id
  from public.diamonds d
  left join public.grievances g on g.id = d.linked_grievance_id
  where d.id = accept_diamond.diamond_id
    and d.status = 'pending'
    and d.linked_grievance_id is not null;

  if v_linked_grievance_id is null then
    return;
  end if;

  update public.diamonds
  set status = 'accepted'
  where id = accept_diamond.diamond_id
    and status = 'pending'
    and linked_grievance_id is not null;

  update public.grievances
  set status = 'resolved',
      resolved_at = now()
  where id = v_linked_grievance_id
    and status != 'resolved';

  if v_grievance_reporter_id is not null then
    update public.profiles
    set points = coalesce(points, 0) + 4
    where id = v_grievance_reporter_id;
  end if;
end;
$$;

create or replace function public.reject_diamond(diamond_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.role in ('admin', 'super_admin')
  ) then
    raise exception 'Only an admin can reject Diamond solutions'
      using errcode = '42501';
  end if;

  -- The status update fires the notification trigger while collaborators still
  -- exist. The rejected post is then removed in the same transaction.
  update public.diamonds
  set status = 'rejected'
  where id = reject_diamond.diamond_id
    and status = 'pending'
    and linked_grievance_id is not null;

  if found then
    delete from public.diamonds
    where id = reject_diamond.diamond_id
      and status = 'rejected';
  end if;
end;
$$;

create or replace function public.get_pending_diamonds()
returns table (
  id bigint,
  user_id uuid,
  body text,
  image_urls text[],
  linked_grievance_id uuid,
  created_at timestamptz,
  user_name text,
  user_avatar text,
  collaborator_count bigint,
  grievance_title text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.role in ('admin', 'super_admin')
  ) then
    raise exception 'Only an admin can review Diamond solutions'
      using errcode = '42501';
  end if;

  return query
  select
    d.id,
    d.user_id,
    d.body,
    d.image_urls,
    d.linked_grievance_id,
    d.created_at,
    coalesce(p.username, 'Unknown'),
    p.avatar_url,
    (select count(*) from public.diamond_collaborators dc where dc.diamond_id = d.id),
    coalesce(g.title, '')
  from public.diamonds d
  left join public.profiles p on p.id = d.user_id
  left join public.grievances g on g.id = d.linked_grievance_id
  where d.status = 'pending'
    and d.linked_grievance_id is not null
  order by d.created_at desc;
end;
$$;

revoke all on function public.add_diamond_collaborator(bigint, uuid) from public, anon;
revoke all on function public.remove_diamond_collaborator(bigint, uuid) from public, anon;
revoke all on function public.accept_diamond(bigint) from public, anon;
revoke all on function public.reject_diamond(bigint) from public, anon;
revoke all on function public.get_pending_diamonds() from public, anon;

grant execute on function public.add_diamond_collaborator(bigint, uuid) to authenticated;
grant execute on function public.remove_diamond_collaborator(bigint, uuid) to authenticated;
grant execute on function public.accept_diamond(bigint) to authenticated;
grant execute on function public.reject_diamond(bigint) to authenticated;
grant execute on function public.get_pending_diamonds() to authenticated;

notify pgrst, 'reload schema';
