-- Persisted, per-user in-app notifications.
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (
    type in (
      'report_approved',
      'report_status',
      'report_removed',
      'diamond_comment',
      'diamond_status',
      'announcement'
    )
  ),
  title text not null,
  body text not null,
  href text,
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  constraint notifications_href_is_internal check (href is null or href like '/%')
);

create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);

create index if not exists notifications_user_unread_idx
  on public.notifications (user_id, created_at desc)
  where read_at is null;

alter table public.notifications enable row level security;
alter table public.notifications replica identity full;

drop policy if exists "Users can read their notifications" on public.notifications;
create policy "Users can read their notifications"
  on public.notifications for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can mark their notifications read" on public.notifications;
create policy "Users can mark their notifications read"
  on public.notifications for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- Default privileges in this project grant broad table access. Restrict this
-- table so clients can only read rows and update the read timestamp.
revoke all on table public.notifications from anon, authenticated;
grant select on table public.notifications to authenticated;
grant update (read_at) on table public.notifications to authenticated;
revoke all on sequence public.notifications_id_seq from anon, authenticated;

create or replace function public.notify_grievance_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_status_label text;
  v_title text := left(coalesce(new.title, 'Community report'), 100);
begin
  if new.reporter_id is null then
    return new;
  end if;

  if new.approved = true and old.approved is distinct from true then
    insert into public.notifications (
      user_id, type, title, body, href, entity_type, entity_id
    ) values (
      new.reporter_id,
      'report_approved',
      'Report approved',
      format('Your report "%s" was approved and published.', v_title),
      '/profile/reports/' || new.id::text,
      'grievance',
      new.id::text
    );
  end if;

  if new.status is distinct from old.status then
    v_status_label := case new.status
      when 'in_progress' then 'in progress'
      when 'in-progress' then 'in progress'
      when 'resolved' then 'resolved'
      when 'public' then 'public'
      when 'submitted' then 'submitted'
      when 'closed' then 'closed'
      else replace(coalesce(new.status, 'updated'), '_', ' ')
    end;

    insert into public.notifications (
      user_id, type, title, body, href, entity_type, entity_id,
      metadata
    ) values (
      new.reporter_id,
      'report_status',
      case new.status
        when 'resolved' then 'Report resolved'
        when 'in_progress' then 'Work started on your report'
        when 'in-progress' then 'Work started on your report'
        else 'Report status updated'
      end,
      format('Your report "%s" is now %s.', v_title, v_status_label),
      '/profile/reports/' || new.id::text,
      'grievance',
      new.id::text,
      jsonb_build_object('status', new.status)
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_notify_grievance_update on public.grievances;
create trigger trg_notify_grievance_update
  after update of approved, status on public.grievances
  for each row
  execute function public.notify_grievance_update();

create or replace function public.notify_grievance_removed()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- Do not create a notification while the user's account itself is being deleted.
  if old.reporter_id is not null
     and exists (select 1 from auth.users where id = old.reporter_id) then
    insert into public.notifications (
      user_id, type, title, body, href, entity_type, entity_id
    ) values (
      old.reporter_id,
      'report_removed',
      'Report removed after review',
      format('Your report "%s" was removed after review.', left(coalesce(old.title, 'Community report'), 100)),
      '/profile/reports',
      'grievance',
      old.id::text
    );
  end if;

  return old;
end;
$$;

drop trigger if exists trg_notify_grievance_removed on public.grievances;
create trigger trg_notify_grievance_removed
  after delete on public.grievances
  for each row
  execute function public.notify_grievance_removed();

create or replace function public.notify_diamond_comment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_owner_id uuid;
  v_actor_name text;
begin
  select d.user_id into v_owner_id
  from public.diamonds d
  where d.id = new.diamond_id;

  if v_owner_id is null or v_owner_id = new.user_id then
    return new;
  end if;

  select coalesce(p.username, 'Someone') into v_actor_name
  from public.profiles p
  where p.id = new.user_id;

  insert into public.notifications (
    user_id, type, title, body, href, entity_type, entity_id,
    metadata
  ) values (
    v_owner_id,
    'diamond_comment',
    coalesce(v_actor_name, 'Someone') || ' commented on your post',
    left(new.body, 180),
    '/diamond',
    'diamond',
    new.diamond_id::text,
    jsonb_build_object('comment_id', new.id, 'actor_id', new.user_id)
  );

  return new;
end;
$$;

drop trigger if exists trg_notify_diamond_comment on public.diamond_comments;
create trigger trg_notify_diamond_comment
  after insert on public.diamond_comments
  for each row
  execute function public.notify_diamond_comment();

create or replace function public.notify_diamond_status()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_notification_title text;
  v_notification_body text;
begin
  if new.status is not distinct from old.status
     or new.status not in ('accepted', 'rejected') then
    return new;
  end if;

  v_notification_title := case new.status
    when 'accepted' then 'Diamond solution accepted'
    else 'Diamond solution not accepted'
  end;
  v_notification_body := case new.status
    when 'accepted' then 'Your direct-solve post was accepted and points were awarded.'
    else 'Your direct-solve post was not accepted after review.'
  end;

  insert into public.notifications (
    user_id, type, title, body, href, entity_type, entity_id,
    metadata
  ) values (
    new.user_id,
    'diamond_status',
    v_notification_title,
    v_notification_body,
    '/diamond',
    'diamond',
    new.id::text,
    jsonb_build_object('status', new.status)
  );

  insert into public.notifications (
    user_id, type, title, body, href, entity_type, entity_id,
    metadata
  )
  select
    c.user_id,
    'diamond_status',
    v_notification_title,
    v_notification_body,
    '/diamond',
    'diamond',
    new.id::text,
    jsonb_build_object('status', new.status)
  from public.diamond_collaborators c
  where c.diamond_id = new.id
    and c.user_id <> new.user_id;

  return new;
end;
$$;

drop trigger if exists trg_notify_diamond_status on public.diamonds;
create trigger trg_notify_diamond_status
  after update of status on public.diamonds
  for each row
  execute function public.notify_diamond_status();

create or replace function public.notify_announcement()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.notifications (
    user_id, type, title, body, href, entity_type, entity_id,
    metadata
  )
  select
    u.id,
    'announcement',
    case new.type
      when 'important_notice' then 'Important notice: ' || left(new.title, 100)
      else 'New announcement: ' || left(new.title, 100)
    end,
    left(new.body, 180),
    '/diamond',
    'announcement',
    new.id::text,
    jsonb_build_object('announcement_type', new.type)
  from auth.users u
  where u.id <> new.author_id;

  return new;
end;
$$;

drop trigger if exists trg_notify_announcement on public.announcements;
create trigger trg_notify_announcement
  after insert on public.announcements
  for each row
  execute function public.notify_announcement();

revoke all on function public.notify_grievance_update() from public, anon, authenticated;
revoke all on function public.notify_grievance_removed() from public, anon, authenticated;
revoke all on function public.notify_diamond_comment() from public, anon, authenticated;
revoke all on function public.notify_diamond_status() from public, anon, authenticated;
revoke all on function public.notify_announcement() from public, anon, authenticated;

-- Enable database-change delivery for the live unread badge when Realtime exists.
do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'notifications'
  ) then
    execute 'alter publication supabase_realtime add table public.notifications';
  end if;
end;
$$;

insert into public.chatbot_knowledge (question, answer, keywords)
values (
  'How do in-app notifications work?',
  'Tap the bell in the top-right corner to see updates about your reports, Diamond posts, comments, and official announcements. The badge shows unread notifications. Tap a notification to open the related screen, or use Mark all read.',
  array['notifications', 'bell', 'unread', 'alerts', 'report updates']
)
on conflict (question) do update
set answer = excluded.answer,
    keywords = excluded.keywords;

notify pgrst, 'reload schema';
